### ISSUE TITLE
Use for ESX

### ISSUE THREAD

**Issue by BronxDre** [onlyserenity/drugsToNPCs#1]
Ive been working on the server.lua in order to get it to work with esx. I dont have any errors in the console but the option of selling is not coming up. Is there any chance you would be able to help me out?

**Comment by onlyserenity** [comment]
You need to have two server events. One that checks the qty of drugs and if qty is greater than 0 then it triggers client event and switch variable has from false to true. Second one does the actual transaction of adding money and removing the item from inventory.
